# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  phantomjs_path: "phantomjs /Users/timothychung/Documents/workspace/stackshare/experiment/wappalyzer/src/drivers/phantomjs/driver.js"

production:
  SECRET_KEY_BASE: e8c0acfa531c08ebc05480c33d6ca57bf10bcee762064b5b13b226b6056afe53d5f60e0c0dcf7309cc662566bed2161f8dedf1a142ee4a98807b5775cfbb38be
  phantomjs_path: "/usr/local/phantomjs/bin/phantomjs --load-images=false --ignore-ssl-errors=yes --ssl-protocol=any /usr/local/wappalyzer/driver.js"